version: '3'

services:
    nginx:
        depends_on:
            - php
        build: ./docker/nginx
        expose:
            - 80
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/etc/sites-enabled/:/etc/nginx/sites-enabled/
        links:
            - php
        restart: always
        environment:
            VIRTUAL_HOST: example.com
    php:
        depends_on:
            - db
        build: ./docker/php7-fpm
        volumes:
            - ./:/var/www/html
        links:
            - db:db
        restart: always
    db:
        image: mariadb:10.3
        volumes:
            - database:/var/lib/mysql
            - ./docker/mysql/conf.d/charset.cnf:/etc/mysql/conf.d/charset.cnf
        environment:
            MYSQL_ROOT_PASSWORD: root
        restart: always

volumes:
    database:

networks:
    default:
        external:
            name: nginx-proxy

